// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: proto/kraken_grid/server.proto

package kraken_grid

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PlaceOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Side          string                 `protobuf:"bytes,1,opt,name=side,proto3" json:"side,omitempty"`              // Order direction: "buy" or "sell"
	Multiplier    int32                  `protobuf:"varint,2,opt,name=multiplier,proto3" json:"multiplier,omitempty"` // Price multiplier, used to calculate the actual price
	Price         float64                `protobuf:"fixed64,3,opt,name=price,proto3" json:"price,omitempty"`          // Price at which to place the order
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlaceOrderRequest) Reset() {
	*x = PlaceOrderRequest{}
	mi := &file_proto_kraken_grid_server_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlaceOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaceOrderRequest) ProtoMessage() {}

func (x *PlaceOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kraken_grid_server_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaceOrderRequest.ProtoReflect.Descriptor instead.
func (*PlaceOrderRequest) Descriptor() ([]byte, []int) {
	return file_proto_kraken_grid_server_proto_rawDescGZIP(), []int{0}
}

func (x *PlaceOrderRequest) GetSide() string {
	if x != nil {
		return x.Side
	}
	return ""
}

func (x *PlaceOrderRequest) GetMultiplier() int32 {
	if x != nil {
		return x.Multiplier
	}
	return 0
}

func (x *PlaceOrderRequest) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

type PlaceOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"` // Whether the operation was successful
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`  // Response message
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlaceOrderResponse) Reset() {
	*x = PlaceOrderResponse{}
	mi := &file_proto_kraken_grid_server_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlaceOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaceOrderResponse) ProtoMessage() {}

func (x *PlaceOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kraken_grid_server_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaceOrderResponse.ProtoReflect.Descriptor instead.
func (*PlaceOrderResponse) Descriptor() ([]byte, []int) {
	return file_proto_kraken_grid_server_proto_rawDescGZIP(), []int{1}
}

func (x *PlaceOrderResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PlaceOrderResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type SetBasePriceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BasePrice     float64                `protobuf:"fixed64,1,opt,name=base_price,json=basePrice,proto3" json:"base_price,omitempty"` // Base price for the order
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetBasePriceRequest) Reset() {
	*x = SetBasePriceRequest{}
	mi := &file_proto_kraken_grid_server_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetBasePriceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetBasePriceRequest) ProtoMessage() {}

func (x *SetBasePriceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kraken_grid_server_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetBasePriceRequest.ProtoReflect.Descriptor instead.
func (*SetBasePriceRequest) Descriptor() ([]byte, []int) {
	return file_proto_kraken_grid_server_proto_rawDescGZIP(), []int{2}
}

func (x *SetBasePriceRequest) GetBasePrice() float64 {
	if x != nil {
		return x.BasePrice
	}
	return 0
}

type SetBasePriceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"` // Whether the operation was successful
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`  // Response message
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetBasePriceResponse) Reset() {
	*x = SetBasePriceResponse{}
	mi := &file_proto_kraken_grid_server_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetBasePriceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetBasePriceResponse) ProtoMessage() {}

func (x *SetBasePriceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kraken_grid_server_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetBasePriceResponse.ProtoReflect.Descriptor instead.
func (*SetBasePriceResponse) Descriptor() ([]byte, []int) {
	return file_proto_kraken_grid_server_proto_rawDescGZIP(), []int{3}
}

func (x *SetBasePriceResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SetBasePriceResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_kraken_grid_server_proto protoreflect.FileDescriptor

const file_proto_kraken_grid_server_proto_rawDesc = "" +
	"\n" +
	"\x1eproto/kraken_grid/server.proto\x12\vkraken_grid\"]\n" +
	"\x11PlaceOrderRequest\x12\x12\n" +
	"\x04side\x18\x01 \x01(\tR\x04side\x12\x1e\n" +
	"\n" +
	"multiplier\x18\x02 \x01(\x05R\n" +
	"multiplier\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x01R\x05price\"H\n" +
	"\x12PlaceOrderResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"4\n" +
	"\x13SetBasePriceRequest\x12\x1d\n" +
	"\n" +
	"base_price\x18\x01 \x01(\x01R\tbasePrice\"J\n" +
	"\x14SetBasePriceResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xbb\x01\n" +
	"\x11KrakenGridService\x12O\n" +
	"\n" +
	"PlaceOrder\x12\x1e.kraken_grid.PlaceOrderRequest\x1a\x1f.kraken_grid.PlaceOrderResponse\"\x00\x12U\n" +
	"\fSetBasePrice\x12 .kraken_grid.SetBasePriceRequest\x1a!.kraken_grid.SetBasePriceResponse\"\x00B\x0fZ\r.;kraken_gridb\x06proto3"

var (
	file_proto_kraken_grid_server_proto_rawDescOnce sync.Once
	file_proto_kraken_grid_server_proto_rawDescData []byte
)

func file_proto_kraken_grid_server_proto_rawDescGZIP() []byte {
	file_proto_kraken_grid_server_proto_rawDescOnce.Do(func() {
		file_proto_kraken_grid_server_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_kraken_grid_server_proto_rawDesc), len(file_proto_kraken_grid_server_proto_rawDesc)))
	})
	return file_proto_kraken_grid_server_proto_rawDescData
}

var file_proto_kraken_grid_server_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_kraken_grid_server_proto_goTypes = []any{
	(*PlaceOrderRequest)(nil),    // 0: kraken_grid.PlaceOrderRequest
	(*PlaceOrderResponse)(nil),   // 1: kraken_grid.PlaceOrderResponse
	(*SetBasePriceRequest)(nil),  // 2: kraken_grid.SetBasePriceRequest
	(*SetBasePriceResponse)(nil), // 3: kraken_grid.SetBasePriceResponse
}
var file_proto_kraken_grid_server_proto_depIdxs = []int32{
	0, // 0: kraken_grid.KrakenGridService.PlaceOrder:input_type -> kraken_grid.PlaceOrderRequest
	2, // 1: kraken_grid.KrakenGridService.SetBasePrice:input_type -> kraken_grid.SetBasePriceRequest
	1, // 2: kraken_grid.KrakenGridService.PlaceOrder:output_type -> kraken_grid.PlaceOrderResponse
	3, // 3: kraken_grid.KrakenGridService.SetBasePrice:output_type -> kraken_grid.SetBasePriceResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_kraken_grid_server_proto_init() }
func file_proto_kraken_grid_server_proto_init() {
	if File_proto_kraken_grid_server_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_kraken_grid_server_proto_rawDesc), len(file_proto_kraken_grid_server_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_kraken_grid_server_proto_goTypes,
		DependencyIndexes: file_proto_kraken_grid_server_proto_depIdxs,
		MessageInfos:      file_proto_kraken_grid_server_proto_msgTypes,
	}.Build()
	File_proto_kraken_grid_server_proto = out.File
	file_proto_kraken_grid_server_proto_goTypes = nil
	file_proto_kraken_grid_server_proto_depIdxs = nil
}
